/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/catalog/{semester}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Page */
        get: operations["catalog_page_api_v1_catalog__semester__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Optimization */
        post: operations["create_optimization_api_v1_optimizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimizations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Optimization */
        get: operations["get_optimization_api_v1_optimizations__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Optimization */
        delete: operations["cancel_optimization_api_v1_optimizations__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Semesters */
        get: operations["semesters_api_v1_semesters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateMetrics */
        CandidateMetrics: {
            /** Campusdays */
            campusDays: number;
            /** Firstclassminute */
            firstClassMinute: number | null;
            /** Gapminutes */
            gapMinutes: number;
            /** Lastclassminute */
            lastClassMinute: number | null;
            /** Totalcredits */
            totalCredits: number;
        };
        /** CatalogPage */
        CatalogPage: {
            /** Datasetversion */
            datasetVersion: string;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Preparedat */
            preparedAt: string;
            /** Sections */
            sections: components["schemas"]["Section"][];
            /** Semester */
            semester: string;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
        };
        /** OptimizationCandidate */
        OptimizationCandidate: {
            /**
             * Changes
             * @default []
             */
            changes: string[];
            /**
             * Explanation
             * @default []
             */
            explanation: string[];
            metrics: components["schemas"]["CandidateMetrics"];
            /** Rank */
            rank: number;
            /** Scorecomponents */
            scoreComponents: {
                [key: string]: number;
            };
            /** Sectionids */
            sectionIds: string[];
            /**
             * Unmetpreferences
             * @default []
             */
            unmetPreferences: string[];
        };
        /** OptimizationCreate */
        OptimizationCreate: {
            /**
             * Candidatecount
             * @default 3
             */
            candidateCount: number;
            /**
             * Candidatecoursecodes
             * @default []
             */
            candidateCourseCodes: string[];
            /** Datasetversion */
            datasetVersion: string;
            /**
             * Excludedcoursecodes
             * @default []
             */
            excludedCourseCodes: string[];
            /**
             * Lockedsectionids
             * @default []
             */
            lockedSectionIds: string[];
            /**
             * Maxcredits
             * @default 18
             */
            maxCredits: number;
            /**
             * Mincredits
             * @default 12
             */
            minCredits: number;
            preferences?: components["schemas"]["OptimizationPreferences"];
            /**
             * Requiredcoursecodes
             * @default []
             */
            requiredCourseCodes: string[];
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Selectedsectionids
             * @default []
             */
            selectedSectionIds: string[];
            /**
             * Semester
             * @default 2026-1
             */
            semester: string;
            /**
             * Timelimitseconds
             * @default 3
             */
            timeLimitSeconds: number;
        };
        /** OptimizationJobRead */
        OptimizationJobRead: {
            /** Attempts */
            attempts: number;
            /** Cancelrequested */
            cancelRequested: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Errorcode */
            errorCode?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
            /** Id */
            id: string;
            request: components["schemas"]["OptimizationCreate"];
            result?: components["schemas"]["OptimizationResult"] | null;
            status: components["schemas"]["OptimizationJobStatus"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * OptimizationJobStatus
         * @enum {string}
         */
        OptimizationJobStatus: "QUEUED" | "RUNNING" | "OPTIMAL" | "FEASIBLE" | "INFEASIBLE" | "TIME_LIMIT" | "FAILED" | "CANCELLED";
        /** OptimizationPreferences */
        OptimizationPreferences: {
            /** Avoidafterminute */
            avoidAfterMinute?: number | null;
            /** Avoidbeforeminute */
            avoidBeforeMinute?: number | null;
            /** Maxdailyminutes */
            maxDailyMinutes?: number | null;
            /**
             * Minimizecampusdays
             * @default true
             */
            minimizeCampusDays: boolean;
            /**
             * Minimizegapminutes
             * @default true
             */
            minimizeGapMinutes: boolean;
            /**
             * Preferreddaysoff
             * @default []
             */
            preferredDaysOff: string[];
        };
        /** OptimizationResult */
        OptimizationResult: {
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["OptimizationCandidate"][];
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Solverversion */
            solverVersion: string;
        };
        /** ReadinessStatus */
        ReadinessStatus: {
            /** Catalog */
            catalog: string;
            /** Database */
            database: string;
            /** Status */
            status: string;
        };
        /** Section */
        Section: {
            /** Category */
            category: string;
            /** Coursecode */
            courseCode: string;
            /** Credits */
            credits: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Professor */
            professor: string | null;
            /** Rawlecturetime */
            rawLectureTime: string;
            /** Roomtobeannounced */
            roomToBeAnnounced: boolean;
            /** Sectioncode */
            sectionCode: string;
            /** Sessions */
            sessions: components["schemas"]["Session"][];
            /** Timetobeannounced */
            timeToBeAnnounced: boolean;
            /**
             * Warningcodes
             * @default []
             */
            warningCodes: string[];
        };
        /** Semester */
        Semester: {
            /** Datasetversion */
            datasetVersion: string;
            /** Id */
            id: string;
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
            /** Preparedat */
            preparedAt: string;
            /** Sectioncount */
            sectionCount: number;
        };
        /** Session */
        Session: {
            /** Buildingcode */
            buildingCode?: string | null;
            /** Buildingname */
            buildingName?: string | null;
            /**
             * Day
             * @enum {string}
             */
            day: "월" | "화" | "수" | "목" | "금" | "토" | "일";
            /** Endminute */
            endMinute: number;
            /** Roomcode */
            roomCode?: string | null;
            /** Roomname */
            roomName?: string | null;
            /** Startminute */
            startMinute: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_page_api_v1_catalog__semester__get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: string | null;
                course_code?: string | null;
                professor?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                semester: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
    create_optimization_api_v1_optimizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_optimization_api_v1_optimizations__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_optimization_api_v1_optimizations__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    semesters_api_v1_semesters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Semester"][];
                };
            };
        };
    };
}
